### PR TITLE
Add processor to format Croatian amounts

### PR DESCRIPTION
**Pull request by nightsh**
* replace decimal separator
* replace group separator

Defining them in the source spec YAML resulted in concatenation of integral and
decimal parts into one big number. Hence the processor.

### CODE REVIEW

**Comment by akariv** [comment]
@nightsh it's more correct to solve the bug and not work around it.
They way you did it at first should have worked fine. Can you create a minimal reproduction (i.e. fake data file & source-spec) demonstrating the bug?

**Comment by nightsh** [comment]
> @nightsh it's more correct to solve the bug and not work around it.
Right, agreed.

> They way you did it at first should have worked fine. Can you create a minimal reproduction (i.e. fake data file & source-spec) demonstrating the bug?
I already did that. First I thought it's a problem because one of the CSV files doesn't have group separators, and the lack of consistence led to unwanted side effects. That's why I went for a processor.
However,  I created a reduced dataset (amounts with both group and decimal separators) with only 5 rows, all the fields. Problem persists, it seems.

Will try to isolate even further by shaving off columns from the data set until I end up with a minimal example.

**Comment by nightsh** [comment]
Isolated to the point where I only had codes and amounts in the dataset, 5 rows in total, all of them with custom group/decimal separators. Values look like a joined string in the database.

In my example, these values:

```
84.719.000,00 | 78.644.000,00 | 77.946.067,23
716.000,00 | 1.155.200,00 | 1.034.332,96
14.599.512,00 | 13.544.512,00 | 13.345.102,23
9.185.000,00 | 9.185.000,00 | 7.463.398,08
3.385.000,00 | 3.880.000,00 | 3.312.059,19
```

end up in postgres like this (sorry for uneven formatting, different clipboard sources):

```
"8471900000"	"7864400000"	"7794606723"
"71600000"	"115520000"	"103433296"
"1459951200"	"1354451200"	"1334510223"
"918500000"	"918500000"	"746339808"
"338500000"	"388000000"	"331205919"
```

An example of measure spec for one of the columns (they're all the same, except names):

```
- header: proposed_value
  title: "Izvorni plan"
  options:
    currency: HRK
    phase: proposed
    decimalChar: ","
    groupChar: "."
  columnType: value
```

**Comment by akariv** [comment]
Can you please open a separate issue with all the source files?

**Comment by nightsh** [comment]
@akariv openspending/openspending#1457

**Comment by nightsh** [comment]
@akariv I saw your [commit](https://github.com/frictionlessdata/tableschema-py/commit/8f1ffb652605c39bd58fddd0372228e1adb5d50d) addressing this.
Please correct me if I'm wrong. We won't need a processor anymore, not even for normalizing the number format, if one out of four data sets in this spec have no group separators.

**Comment by akariv** [comment]
Correct - can you try the patch and see if it works for you (install the tableschema version from my branch)?

**Comment by nightsh** [comment]
@akariv all good, just tested now.

**Comment by akariv** [comment]
:+1:

**Comment by nightsh** [comment]
Closing as obsoleted by frictionlessdata/tableschema-py#236 and closed for tableschema-py in https://github.com/frictionlessdata/tableschema-py/commit/15babd1972d279fd503473097447adcd1ad905dc

**Pull request closed without merging**
